name: Build CI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm i
    - env:
        REACT_APP_PROJ_CONFIG: ${{ secrets.PROJ_CONFIG }}
        REACT_APP_CI: true
      run: npm run build
    - run: mv build happy-table
      shell: bash
    - name: Archive production build
      uses: actions/upload-artifact@v3
      with:
        name: happy-table
        path: |
          happy-table
